```{r "setup", include=FALSE}
rm(list = ls())

knitr::opts_knit$set(root.dir = '~/Documents/work/Sex-differences-of-Pneumoccocal-colonization/')

pkgs <- c('tidyverse','data.table','ggplot2')
suppressPackageStartupMessages(sapply(pkgs, require, character.only = T))

studies = c('MUCOSAL','LAIV1','LAIV2','AGES')
```
# 5) Montar Fig1A com as informações do item 4. Quais desses grupos podem ser usados (N >= 2)?

```{r}
pheno.all <- list.files('data/tidy_data/tables/', pattern = 'pheno', full.names = T) %>%
  lapply(fread, data.table = F) %>%
  Reduce(rbind,.)
head(pheno.all)
```

```{r}
plt <- ggplot(pheno.all, aes(class, fill = class)) + geom_bar(show.legend = F) + coord_flip() +
  facet_grid(study~., scales = 'free') + theme_linedraw() + 
  geom_text(stat = 'count', aes(text = ..count.., label = ..count..), hjust = -.5) +
  labs(x = 'Classes', y = 'Number of Samples', title = 'Fig. 1A', subtitle = 'Number of Samples by Group') +
  ylim(c(0,30)) + theme(panel.grid.major = element_blank())
plt
```
```{r}
pdf('intermediate/item5_fig1A/fig1A.pdf')
plt
dev.off()
```

