## Evaluate p-value thresholds

### Settings

```{r "setup", include=FALSE}
rm(list = ls())

basedir <- '~/Documents/work/Sex-differences-of-Pneumoccocal-colonization/'
outdir = file.path(basedir,'intermediate/item6_DEtables/')
if(!dir.exists(outdir)) dir.create(outdir)
knitr::opts_knit$set(root.dir = basedir)

pkgs <- c('tidyverse','data.table','ggplot2')
suppressPackageStartupMessages(sapply(pkgs, require, character.only = T))
```

### Load Data

```{r}
fnames <- list.files(outdir, full.names = T, pattern = 'edgeR_topTable')
de.table <- lapply(fnames, fread, data.table = F) %>% Reduce(rbind, .)
de.table = de.table %>% mutate(group_name = paste0(dataset_name,'_',group_name))
head(de.table)
```

### Non-adjusted p-value

```{r}
pvalues <- seq(0,.1,.01)

deg_byPvalThrs <- lapply(pvalues, function(pval) {
  de.table %>% filter(abs(logFC) > 0, PValue < pval) %>% 
    group_by(group_name) %>%
    summarise(num_deg = n()) %>% 
    mutate(pval_thrs = pval)
}) %>% Reduce(rbind, .) %>% 
  separate(group_name, into = c('dataset','carriage','sex'),remove = F)
deg_byPvalThrs
```

```{r}
plt_study <- ggplot(deg_byPvalThrs, aes(-log10(pval_thrs), num_deg, group = group_name, col = dataset)) +
  geom_point() + geom_line() +  labs(x = '-log10(p-value)', y = 'Number of DEGs') + theme_minimal() +
  geom_hline(yintercept = c(100, 1000), col = 'red') +
  geom_vline(xintercept = c(-log10(0.01),-log10(0.05),-log10(0.1)), linetype ='dashed')
plt_study
```

Color by sex

```{r}
plt_sex <- ggplot(deg_byPvalThrs, aes(-log10(pval_thrs), num_deg, group = group_name, col = sex)) + 
  geom_point() + geom_line() +  labs(x = '-log10(p-value)', y = 'Number of DEGs', col = 'Sex') + theme_minimal() +
  geom_hline(yintercept = c(100, 1000), col = 'red') +
  geom_vline(xintercept = c(-log10(0.01),-log10(0.05),-log10(0.1)), linetype ='dashed')
plt_sex
```

Color by carriage

```{r}
plt_carriage <- ggplot(deg_byPvalThrs, aes(-log10(pval_thrs), num_deg, group = group_name, col = carriage)) + 
  geom_point() + geom_line() +  labs(x = '-log10(p-value)', y = 'Number of DEGs', col = 'Carriage') + theme_minimal() +
  geom_hline(yintercept = c(100, 1000), col = 'red') +
  geom_vline(xintercept = c(-log10(0.01),-log10(0.05),-log10(0.1)), linetype ='dashed')
plt_carriage
```

Color by Sex and Carriage

```{r}
plt_sex_carriage <- ggplot(deg_byPvalThrs, aes(-log10(pval_thrs), num_deg, group = paste0(dataset, group_name), col = paste0(carriage, '_',sex))) + 
  geom_point() + geom_line() +  labs(x = '-log10(p-value)', y = 'Number of DEGs', col = 'Carriage + Sex') + theme_minimal() +
  geom_hline(yintercept = c(100, 1000), col = 'red') +
  geom_vline(xintercept = c(-log10(0.01),-log10(0.05),-log10(0.1)), linetype ='dashed')
plt_sex_carriage
```

```{r}
pdf(file.path(outdir, 'numDEGs_by_pval_thresholds_assessment.pdf'))
plt_study
plt_sex
plt_carriage
plt_sex_carriage
dev.off()
```

### Adjusted p-value

```{r}
pvalues <- seq(0,.1,.01)

deg_byFDRThrs <- lapply(pvalues, function(pval) {
  de.table %>% filter(abs(logFC) > 0, FDR < pval) %>% 
    group_by(group_name) %>%
    summarise(num_deg = n()) %>% 
    mutate(pval_thrs = pval)
}) %>% Reduce(rbind, .) %>% 
  separate(group_name, into = c('dataset','carriage','sex'),remove = F)
deg_byFDRThrs
```

```{r}
plt <- ggplot(deg_byFDRThrs, aes(-log10(pval_thrs), num_deg, group = group_name, col = dataset)) + 
  geom_point() + geom_line() + labs(x = '-log10(FDR)', y = 'Number of DEGs') + theme_minimal() + 
  geom_hline(yintercept = c(100, 1000), col = 'red') +
  geom_vline(xintercept = c(-log10(0.01),-log10(0.05),-log10(0.1)), linetype ='dashed')
plt
```

```{r}
pdf(file.path(outdir, 'numDEGs_by_FDR_thresholds_assessment.pdf'))
plt
dev.off()
```

## Plot Number of DEGs by Group

```{r}
pval = 0.01
num_degs <- de.table %>% filter(PValue < pval) %>% 
  mutate(deg = ifelse(logFC > 0,1, 0), deg = ifelse(logFC < 0, -1, deg)) %>% 
  group_by(group_name, deg) %>%
  summarise(num_deg = n()) %>% 
  separate(group_name, into = c('dataset','carriage','sex'),remove = F) 
num_degs
```
```{r}
plt.num_degs <- ggplot(num_degs, aes(sex, deg*num_deg, fill = ifelse(deg > 0, 'Up', 'Down'))) +
  geom_bar(stat = 'identity') +
  facet_grid(.~dataset + carriage) +theme_linedraw() +
  scale_fill_manual(values = c('dodgerblue3','darkred')) +
  labs(x = 'Sex', y = 'Number of DEGs', fill = 'Direction') +
  theme(panel.grid = element_blank())
  
plt.num_degs
```
```{r}
pdf(file.path(outdir, 'num_degs_pval-01_barplot.pdf'), width = 10)
plt.num_degs
dev.off()
```
Save Num. DEGs Table
```{r}
num_degs %>% 
  mutate(deg = ifelse(deg == -1, 'Down', 'Up')) %>% 
  spread(key = deg,value = num_deg) %>% 
  fwrite(file.path(outdir, 'num_deg_pval-01_table.csv'), sep = '\t', quote = F, row.names = F)

```

