# Calculate meta-DEGs

### Settings

```{r "setup", include=FALSE}
rm(list = ls())

basedir <- '~/Documents/work/Sex-differences-of-Pneumoccocal-colonization/'
outdir = file.path(basedir,"intermediate/item7_metaDEGs/")
knitr::opts_knit$set(root.dir = basedir)

pkgs <- c('tidyverse','data.table','ggplot2','metap')
suppressPackageStartupMessages(sapply(pkgs, require, character.only = T))
```

```{r}
if(!dir.exists(outdir)) dir.create(outdir)
```

### Load Data

```{r}
fnames <- list.files('intermediate/item6_DEtables/', pattern = 'edgeR_topTable', full.names = T)
de.tables <- lapply(fnames, fread, data.table = F) %>% setNames(gsub('edgeR_topTable_|\\.csv','',basename(fnames)))
```

## Estimate meta-Pvalue using Fischer method

Bind PValue Columns

```{r}
pval.df <- lapply(names(de.tables), function(group.name) {
  de.tables[[group.name]] %>% select(gene_id, PValue) %>% 
    setNames(c('gene_id',group.name))
}) %>% Reduce(function(x ,y) merge(x, y, by = 'gene_id', all = T), .) %>% 
  column_to_rownames('gene_id')
```

Remove rows (genes) with only one P-value

```{r}
keep = rowSums(!is.na(pval.df)) > 1
```

Calculate Combined p-values with Fischer Method

```{r}
pCombined <- apply(pval.df[keep,], 1, function(x) sumlog(x[!is.na(x)])$p )
```

```{r}
pdf(file.path(outdir,'DEGs_vs_PValueThrs.pdf'))

hist(pCombined)

num_degs <- data.frame(pvalues = seq(0,0.1,.01)) %>% 
  mutate(num_degs = sapply(pvalues, function(pval) sum(pCombined < pval)))
ggplot(num_degs, aes(-log10(pvalues), num_degs)) + geom_line() + geom_point() +
  geom_vline(xintercept = c(-log10(.01),-log10(.05),-log10(.1)), linetype = 'dashed') +
  geom_hline(yintercept = c(100, 1000), col = 'red')
dev.off()
```

Adjust combined p-values (FDR)

```{r}
FDR <- p.adjust(pCombined, method = "fdr", n = length(pCombined))
```

```{r}
pdf(file.path(outdir,'DEGs_vs_FDRThrs.pdf'))
hist(FDR)

num_degs <- data.frame(pvalues = seq(0,0.1,.01)) %>% 
  mutate(num_degs = sapply(pvalues, function(pval) sum(FDR < pval)))
ggplot(num_degs, aes(-log10(pvalues), num_degs)) + geom_line() + geom_point() +
  geom_vline(xintercept = c(-log10(.01),-log10(.05),-log10(.1)), linetype = 'dashed') +
  geom_hline(yintercept = c(100, 1000), col = 'red')
dev.off()
```

Save p-values table

```{r}
pval.df[names(pCombined),'pCombined'] = pCombined
pval.df[names(pCombined),'FDR'] = FDR
pval.df %>% rownames_to_column('gene_id') %>% 
  fwrite(file.path(outdir, 'combinedPval_FischerMethod.csv'), sep = '\t', quote = F, row.names = F)
```
