

```{r }
rm(list = ls())
pkgs <- c('tidyverse','data.table')
suppressPackageStartupMessages(sapply(pkgs, require, character.only = T))

studies = c('MUCOSAL','LAIV1','LAIV2','AGES')

dir.create('data/tidy_data/Rdata/', recursive = T, showWarnings = F)
dir.create('data/tidy_data/tables/', recursive = T, showWarnings = F)
```


```{r }
meta <- fread('data/raw_data/EHPC_Density_Data_12MARCH2020.tsv') %>% data.frame(row.names = 'sample_id') %>%
  mutate(study = toupper(study)) %>% filter(study %in% studies, !duplicated(volunteer_id)) %>% select(-timepoint)
head(meta)
```

Adult1 (Baseline, Day 2)
```{r}
mucosal.counts <- fread('data/raw_data/PILOT_rnaseq_data.tsv') %>% data.frame(row.names = 1)
mucosal.pheno <- fread('data/raw_data/PILOT_rnaseq_meta.tsv',data.table = F)
identical(colnames(mucosal.counts), mucosal.pheno$sample_id)

mucosal.pheno = mucosal.pheno %>% mutate(carriage = carriage_status) %>%
  merge(meta[c('volunteer_id', 'sex')], by = 'volunteer_id', all.x = T) %>% 
  select(sample_id, volunteer_id, timepoint, study, carriage, sex, vaccine) %>% 
  mutate(group = 'Study1') %>% 
  unite('class', group, carriage, sex, sep = '_') %>% 
  relocate(-class)

identical(colnames(mucosal.counts), mucosal.pheno$sample_id)
Adult1 <- list(counts = mucosal.counts, pheno = mucosal.pheno)
saveRDS(Adult1, 'data/tidy_data/Rdata/Adult1.rds')
Adult1$counts %>% cbind(gene_id = rownames(.),.) %>% fwrite('data/tidy_data/tables/Adult1_counts.csv', row.names = F, sep = '\t')
Adult1$pheno %>% fwrite('data/tidy_data/tables/Adult1_pheno.csv', row.names = F, sep = '\t')
```

Adult2 (TIV, Basline and Day 6)
```{r}
laiv1.counts <- fread('data/raw_data/LAIV1_rnaseq_data.tsv') %>% data.frame(row.names = 1)
laiv1.pheno <- fread('data/raw_data/LAIV1_rnaseq_meta.tsv', data.table = F) %>% mutate(sample_id = sample_id_original)
identical(colnames(laiv1.counts), laiv1.pheno$sample_id)

laiv1.pheno = laiv1.pheno %>% filter(vaccine == 'TIV', timepoint %in% c('baseline','D6')) %>%
  mutate(carriage = carriage_status) %>%
  merge(meta[c('volunteer_id', 'sex')], by = 'volunteer_id', all.x = T)
laiv1.pheno = laiv1.pheno[,c('sample_id', 'volunteer_id', 'timepoint', 'study', 'carriage', 'sex', 'vaccine')]
laiv1.pheno$group = 'Adults2'
laiv1.pheno = laiv1.pheno %>% unite('class', c(group, carriage, sex), sep = '_')

laiv1.counts = laiv1.counts[,laiv1.pheno$sample_id]

identical(colnames(laiv1.counts), laiv1.pheno$sample_id)
Adult2 <- list(counts = laiv1.counts, pheno = laiv1.pheno)
saveRDS(Adult2, 'data/tidy_data/Rdata/Adult2.rds')
Adult2$counts %>% cbind(gene_id = rownames(.),.) %>% fwrite('data/tidy_data/tables/Adult2_counts.csv', row.names = F, sep = '\t')
Adult2$pheno %>% fwrite('data/tidy_data/tables/Adult2_pheno.csv', row.names = F, sep = '\t')
```

Adult3 (Baseline, Day 2)
```{r}
laiv2.counts <- fread('data/raw_data/LAIV2_rnaseq_data.tsv') %>% data.frame(row.names = 1)
laiv2.pheno <- fread('data/raw_data/LAIV2_rnaseq_meta.txt', data.table = F) %>% mutate(sample_id = sample_id_original)
laiv2.counts = laiv2.counts[,laiv2.pheno$sample_id]
identical(laiv2.pheno$sample_id, colnames(laiv2.counts))

laiv2.pheno = laiv2.pheno %>% filter(timepoint %in% c('baseline', 'D2')) %>% 
  mutate(study = 'LAIV2', group = 'Adults3') %>%
  select(sample_id, volunteer_id, timepoint, study, carriage, sex, vaccine, group) %>%
  unite('class', group, carriage, sex, sep = '_') %>% 
  relocate(-class)
head(laiv2.pheno)

identical(laiv2.pheno$sample_id, colnames(laiv2.counts))
Adult3 <- list(counts = laiv2.counts, pheno = laiv2.pheno)
saveRDS(Adult3, 'data/tidy_data/Rdata/Adult3.rds')
Adult3$counts %>% cbind(gene_id = rownames(.),.) %>% fwrite('data/tidy_data/tables/Adult3_counts.csv', row.names = F, sep = '\t')
Adult3$pheno %>% fwrite('data/tidy_data/tables/Adult3_pheno.csv', row.names = F, sep = '\t')
```

Elderly1 (Baseline, Day 2)
```{r}
suppressPackageStartupMessages(library(MultiAssayExperiment))
data <- readRDS('data/raw_data/AGES_studyObj.rds')
data <- data[['RNA-Seq']]
data <- data[,which(data$timepoint %in% c('baseline','D2'))]
data$study <- 'AGES'
data$vaccine <- 'NoVac'
colnames(data) <- data$sample_id

ages.counts <- assay(data)
ages.pheno <- colData(data) %>% as.data.frame %>% 
  select(sample_id, volunteer_id, timepoint, study, carriage, sex, vaccine) %>% 
  mutate(group = 'Elderly1') %>% 
  unite('class', group,carriage, sex, sep = '_') %>%
  relocate(-class)

identical(colnames(ages.counts),ages.pheno$sample_id)
Elderly1 <- list(counts = ages.counts, pheno = ages.pheno)
saveRDS(Elderly1, 'data/tidy_data/Rdata/Elderly1.rds')
Elderly1$counts %>% cbind(gene_id = rownames(.),.) %>% fwrite('data/tidy_data/tables/Elderly1_counts.csv', row.names = F, sep = '\t')
Elderly1$pheno %>% fwrite('data/tidy_data/tables/Elderly1_pheno.csv', row.names = F, sep = '\t')
```

