---
title: "Paper Sex-differences of Pneumoccocal colonization"
output: html_notebook
---

# Paper Sex-differences of Pneumoccocal colonization

## 1) Separar datasets

1.  Dataset 1 (Piloto): Usar Baseline e D2 post-challenge

2.  Dataset 2 (LAIV1): Usar apenas as pessoas que receberam TIV (controle) e pegar Baseline e D6 (post-challenge). NÃO pegar as pessoas que receberam LAIV e nem o time point D2 post-immunization.

3.  Dataset 3 (LAIV2): Usar todo mundo (já que as vacinas foram depois da inoculação) e o Baseline e D2 post-challenge

4.  Dataset 4  (AGES): Usar Baseline e D2 post-challenge

## 2) Nomes das coortes:

1.  Dataset 1 (Piloto): Adult1

2.  Dataset 2 (LAIV1): Adult2

3.  Dataset 3 (LAIV2): Adult3

4.  Dataset 4  (AGES):  Elderly1

## 3) Anotar as amostras pela classe: Positive or Negative 

1.  Dataset 1 (Piloto): Adult1_Positive e Adult1_Negative

2.  Dataset 2 (LAIV1): Adult2_Positive e Adult2_Negative

3.  Dataset 3 (LAIV2): Adult3_Positive e Adult3_Negative

4.  Dataset 4  (AGES):  Elderly1_Positive e Elderly1_Negative

## 4) Contar o número de amostras por sexo

1.   Dataset 1 (Piloto): Adult1_Positive_Male (N?),  Adult1_Negative_Male (N?), Adult1_Positive_Female (N?),  Adult1_Negative_Female (N?)

2.  Dataset 2 (LAIV1): Adult2_Positive_Male (N?),  Adult2_Negative_Male (N?), Adult2_Positive_Female (N?),  Adult2_Negative_Female (N?)

3.  Dataset 3 (LAIV2): Adult3_Positive_Male (N?),  Adult3_Negative_Male (N?), Adult3_Positive_Female (N?),  Adult3_Negative_Female (N?)

4.  Dataset 4  (AGES):  Elderly1_Positive_Male (N?),  Elderly1_Negative_Male (N?), Elderly1_Positive_Female (N?),  Elderly1_Negative_Female (N?)

## 5) Montar Fig1A com as informações do item 4. Quais desses grupos podem ser usados (N \>= 2)?

## 6) DEG per cohort (EdgeR use um FDR cutoff que dê entre 100 a 1000 DEGs). 

1.  Adult1_Positive_Male_D2v0 (pareado)

2.  Adult2_Positive_Male_D2v0 (pareado)

3.  Adult3_Positive_Male_D2v0 (pareado)

4.  Elderly1_Positive_Male_D2v0 (pareado)

    ...repetir para TODOS que tem pelo menos 2 amostras.

## 7) Com as tabelas de DEG do item 6 (ou seja, contendo TODOS os genes e seus p, Adj P, log2FC e se é up (1) ou down (-1)), junte tudo em uma grande tabela.

1.  Usar essa tabela pra plotar o vote-count de DEG (meta-volcano). Trate só os adults. Quantos DEGs aparecem em pelo menos 1, 2 ou nas 3 cohorts na mesma direção?

2.  Usar essa tabela pra plotar o vote-count de DEG (meta-volcano). Trate só os adults + elderly. Quantos DEGs aparecem em pelo menos 1, 2, 3 ou nas 4 cohorts na mesma direção?

3.  Rode o metavolcano OU o meta-P usando Fisher method para combinar os P-values e depois calcule o FDR BH. Trate só os adults. Quantos DEGs aparecem pra cada direção usando um FDR \< X (pegue um cutoff entre 100 a 1000)?

4.  Rode o metavolcano OU o meta-P usando Fisher method para combinar os P-values e depois calcule o FDR BH. Trate só os adults + elderly. Quantos DEGs aparecem pra cada direção usando um FDR \< X (pegue um cutoff entre 100 a 1000)?\

## 8) Pathway enrichment analysis com os DEGs.

1.  Pegue os DEGs do item 6.1 e rode enrichR (clusterProfile) com Reactome. 

2.  Pegue os DEGs do item 6.2 e rode enrichR (clusterProfile) com Reactome.

...X. Pegue os DEGs do item 7.4 e rode enrichR (clusterProfile) com Reactome.   \

## 9) Junte todos os pathways e seus -log10AdjP das tabelas do item 8

Iremos olhar a tabela e decidir quais pathways destacar.

## 10) Pegue o ranking (log2FC pareado D2v0) de todas as comparações do item 6 e rode o fGSEA com Reactome, GO BP, KEGG  e BioCarta. Pegue os gmt do EnrichR. 

## 11) Pegue o ranking (meta-log2FC D2v0) do item 7 e rode o fGSEA com Reactome, GO BP, KEGG  e BioCarta. Pegue os gmt do EnrichR.

## 12) Junte os NES (dos casos em que o Adj P \< 0.1) dos item 10 e 11 em 1 tabela para decidir quais são interessantes.

## 13) CEMiTool usando como classes o sexo e o fato se é positivo ou negativo

1.  Dataset 1 (Piloto): Adult1

2.  Dataset 2 (LAIV1): Adult2

3.  Dataset 3 (LAIV2): Adult3

4.  Dataset 4  (AGES):  Elderly1

## 14) Combine os resultados do enrichR per module per dataset. Use Reactome. 

## 15) Combine os resultados do GSEA per module per dataset. Isso é pra ver se cada módulo aparece aumentado ou diminuído em positivo, female, etc 

## 16) Cruze os módulos dos dos datasets para achar os meta-modules

Cada edge (par de genes em um módulo) pode ter um valor de 1 a 4 (4 se esse par estiver em módulos nos 4 datasets)

## 17) Crie a rede usando edges do item 16.

1.  Use edges com valores de 2+ (o par de genes tem que estar em módulos de pelo menos 2 dos 4 datasets)

    1.  Não faça nenhuma análise funcional ainda.

    2.  Use o estas edges para construir uma rede (gephi) e rode a análise de modularidade. Os módulos revelados pelo gephi serão as CM (Community Modules). Exporte as CMs para as análises funcionais.

2.  Use edges com valores de 3 ou 4 (o par de genes tem que estar em módulos de pelo menos 2 dos 4 datasets)

    1.  Não faça nenhuma análise funcional ainda.

    2.  Use o estas edges para construir uma rede (gephi) e rode a análise de modularidade. Os módulos revelados pelo gephi serão as CM (Community Modules). Exporte as CMs para as análises funcionais.

## 18) Faça enriquecimento de pathways com as CMs do item 17.

1.  CM de 17.1 vs Reactome

2.  CM de 17.2 vs Reactome\

## 19) Junte as tabelas do item 18 para olharmos.
